<?php
$router->get('/login',[AuthController::class,'login']);
$router->post('/login',[AuthController::class,'login']);
$router->get('/logout',[AuthController::class,'logout']);
$router->get('/',[DashboardController::class,'index']);
$router->get('/dashboard',[DashboardController::class,'index']);
$router->get('/manager/company',[ManagerController::class,'index']);
$router->get('/hr/employees',[HrController::class,'index']);
$router->get('/spec-books',[SpecBookController::class,'index']);
$router->get('/orders',[OrdersController::class,'index']);
$router->get('/shopfloor/items',[ShopfloorController::class,'index']);
$router->get('/wms/warehouses',[WmsController::class,'index']);
$router->get('/planner',[PlannerController::class,'index']);
$router->get('/calendar',[CalendarController::class,'index']);
$router->get('/audits',[AuditsController::class,'index']);
$router->get('/tasks',[TasksController::class,'index']);
$router->get('/reports',[ReportsController::class,'index']);
$router->get('/settings/users',[SettingsController::class,'index']);
